# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmEncriptar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmEncriptar(object):
    def setupUi(self, FrmEncriptar):
        FrmEncriptar.setObjectName("FrmEncriptar")
        FrmEncriptar.resize(691, 518)
        self.centralwidget = QtWidgets.QWidget(FrmEncriptar)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 60, 481, 161))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 280, 471, 171))
        self.label_3.setObjectName("label_3")
        FrmEncriptar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FrmEncriptar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 21))
        self.menubar.setObjectName("menubar")
        FrmEncriptar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrmEncriptar)
        self.statusbar.setObjectName("statusbar")
        FrmEncriptar.setStatusBar(self.statusbar)

        self.retranslateUi(FrmEncriptar)
        QtCore.QMetaObject.connectSlotsByName(FrmEncriptar)

    def retranslateUi(self, FrmEncriptar):
        _translate = QtCore.QCoreApplication.translate
        FrmEncriptar.setWindowTitle(_translate("FrmEncriptar", "MainWindow"))
        self.label.setText(_translate("FrmEncriptar", "Mensaje"))
        self.pushButton.setText(_translate("FrmEncriptar", "Encriptar"))
        self.pushButton_2.setText(_translate("FrmEncriptar", "Cargar Archivo"))
        self.pushButton_3.setText(_translate("FrmEncriptar", "Limpiar"))
        self.pushButton_4.setText(_translate("FrmEncriptar", "Guardar Archivo"))
        self.label_2.setText(_translate("FrmEncriptar", "Encriptado"))
        self.label_3.setText(_translate("FrmEncriptar", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmEncriptar = QtWidgets.QMainWindow()
    ui = Ui_FrmEncriptar()
    ui.setupUi(FrmEncriptar)
    FrmEncriptar.show()
    sys.exit(app.exec_())
