# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmMenu(object):
    def setupUi(self, FrmMenu):
        FrmMenu.setObjectName("FrmMenu")
        FrmMenu.resize(637, 470)
        self.centralwidget = QtWidgets.QWidget(FrmMenu)
        self.centralwidget.setObjectName("centralwidget")
        FrmMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FrmMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 637, 21))
        self.menubar.setObjectName("menubar")
        self.menuEncriptar = QtWidgets.QMenu(self.menubar)
        self.menuEncriptar.setObjectName("menuEncriptar")
        self.menuDesencriptar = QtWidgets.QMenu(self.menubar)
        self.menuDesencriptar.setObjectName("menuDesencriptar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        FrmMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrmMenu)
        self.statusbar.setObjectName("statusbar")
        FrmMenu.setStatusBar(self.statusbar)
        self.actionDesencriptar = QtWidgets.QAction(FrmMenu)
        self.actionDesencriptar.setObjectName("actionDesencriptar")
        self.actionOpciones = QtWidgets.QAction(FrmMenu)
        self.actionOpciones.setObjectName("actionOpciones")
        self.encriptarNuevo = QtWidgets.QAction(FrmMenu)
        self.encriptarNuevo.setObjectName("encriptarNuevo")
        self.desencriptarNuevo = QtWidgets.QAction(FrmMenu)
        self.desencriptarNuevo.setObjectName("desencriptarNuevo")
        self.menuEncriptar.addAction(self.encriptarNuevo)
        self.menuDesencriptar.addAction(self.desencriptarNuevo)
        self.menubar.addAction(self.menuEncriptar.menuAction())
        self.menubar.addAction(self.menuDesencriptar.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(FrmMenu)
        QtCore.QMetaObject.connectSlotsByName(FrmMenu)

    def retranslateUi(self, FrmMenu):
        _translate = QtCore.QCoreApplication.translate
        FrmMenu.setWindowTitle(_translate("FrmMenu", "Sistema de encriptacion de archivos"))
        self.menuEncriptar.setTitle(_translate("FrmMenu", "Encriptar"))
        self.menuDesencriptar.setTitle(_translate("FrmMenu", "Desencriptar"))
        self.menuOpciones.setTitle(_translate("FrmMenu", "Opciones"))
        self.menuAyuda.setTitle(_translate("FrmMenu", "Ayuda"))
        self.actionDesencriptar.setText(_translate("FrmMenu", "Desencriptar"))
        self.actionOpciones.setText(_translate("FrmMenu", "Opciones"))
        self.encriptarNuevo.setText(_translate("FrmMenu", "Nuevo"))
        self.desencriptarNuevo.setText(_translate("FrmMenu", "Nuevo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmMenu = QtWidgets.QMainWindow()
    ui = Ui_FrmMenu()
    ui.setupUi(FrmMenu)
    FrmMenu.show()
    sys.exit(app.exec_())
